PCA

In [1]:
import numpy as np
from sklearn.datasets import load_iris

X = load_iris()["data"]

a. First make the data zero centered by subtracting mean of each column from the column itself

In [2]:
def normalize(X):
    for i in range(X.shape[1]):
        X[:,i] =  X[:,i] - X[:,i].mean()
    return X

In [3]:
X_norm = normalize(X)
print(X_norm[0,:])

[-0.74333333  0.44266667 -2.358      -0.99933333]


b. Find the covariance matrix of the data using the following formula

In [4]:
def covariance(X):
    X = X.T.dot(X)/X.shape[0]
    return X

In [5]:
S = covariance(X_norm)
print(S)

[[ 0.68112222 -0.04215111  1.26582     0.51282889]
 [-0.04215111  0.18871289 -0.32745867 -0.12082844]
 [ 1.26582    -0.32745867  3.09550267  1.286972  ]
 [ 0.51282889 -0.12082844  1.286972    0.57713289]]


c. Find the eigenvalues of the covariance matrix and their corresponding eigenvectors in ordered manner, do not forget the sort the eigenvalues in descending order. You can use np.linalg.eig() function to find eigenvalues and eigenvectors

In [6]:
def eigen(S):
    eigen_value, eigen_matrix = np.linalg.eig(S)
    return eigen_value, eigen_matrix

In [7]:
eigen_value, eigen_matrix = eigen(S)
print(eigen_value)
print(eigen_matrix)

[4.20005343 0.24105294 0.0776881  0.02367619]
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]


d. Lastly use the first k columns of the eigenmatrix to make the transformation 

In [8]:
def transform(X,B,k):
    X_transformed = X.dot(B[:,:k])
    return X_transformed

In [9]:
X_transformed = transform(X_norm, eigen_matrix, 4)
print(X_transformed[0,:])

[-2.68412563e+00 -3.19397247e-01 -2.79148276e-02  2.26243707e-03]
